const ITEM_TYPE: Record<string, string> = {
  '$': 'Treasure',
  '$A': 'Art Object',
  '$C': 'Coinage',
  '$G': 'Gemstone',
  'A': 'Ammunition',
  'AF': 'Futuristic Ammunition',
  'AIR': 'Air Vehicle',
  'AT': 'Artisan Tool',
  'EXP': 'Explosive',
  'FD': 'Food and Drink',
  'G': 'Adventuring Gear',
  'GS': 'Gaming Set',
  'GV': 'Generic Variant',
  'HA': 'Heavy Armor',
  'IDG': 'Illegal Drug',
  'INS': 'Instrument',
  'LA': 'Light Armor',
  'M': 'Melee Weapon',
  'MA': 'Medium Armor',
  'MNT': 'Mount',
  'OTH': 'Other',
  'P': 'Potion',
  'R': 'Ranged Weapon',
  'RD': 'Rod',
  'RG': 'Ring',
  'S': 'Shield',
  'SC': 'Scroll',
  'SCF': 'Spellcasting Focus',
  'SHP': 'Water Vehicle',
  'SPC': 'Space Vehicle',
  'T': 'Tool',
  'TAH': 'Tack and Harness',
  'TB': 'Trade Bar',
  'TG': 'Trade Good',
  'VEH': 'Land Vehicle',
  'WD': 'Wand',
};

export function expandItemType(code: string): string {
  return ITEM_TYPE[code] ?? code;
}
